services:
  logging:
    environments:
      myproject-prod:
        project_id: my-prod-project
      myproject-dev:
        project_id: my-dev-project
  cloudrun:
    environments:
      myproject-prod:
        project_id: my-prodk-project
        region: us-central1
  gke:
    environments:
      apps-prod:
        project_id: my-prodk-project
        region: us-central1
  spanner:
    environments:
      prod:
        project_id: my-spanner-prod-project
      dev:
        project_id: my-spanner-dev-project